#ifndef RAPTURE__TERRAIN_TYPES_H
#define RAPTURE__TERRAIN_TYPES_H

#include "Buffers/Descriptors/DescriptorSet.h"
#include "Buffers/StorageBuffers/StorageBuffer.h"

#include <glm/glm.hpp>

#include <cstdint>
#include <functional>
#include <memory>

namespace Rapture {

// Vertex format matching the compute shader output
struct TerrainVertex {
    glm::vec3 position;
    float pad0;
    glm::vec3 normal;
    float pad1;
    glm::vec2 uv;
    glm::vec2 pad2;
};

/**
 * @brief Represents a single terrain chunk with cached geometry.
 */
struct TerrainChunk {
    glm::ivec2 coord{0, 0}; // Grid coordinate
    uint32_t lod = 0;

    // Cached geometry (generated by compute shader)
    std::unique_ptr<StorageBuffer> vertexBuffer;
    std::unique_ptr<StorageBuffer> indexBuffer;
    std::unique_ptr<DescriptorSet> descriptorSet;
    uint32_t vertexCount = 0;
    uint32_t indexCount = 0;

    // Offsets into shared buffers (if using large shared buffers)
    uint32_t vertexOffset = 0;
    uint32_t indexOffset = 0;

    // Bounds for culling
    float minHeight = 0.0f;
    float maxHeight = 0.0f;

    // State
    enum class State : uint8_t {
        Unloaded,
        Generating, // Compute shader generating geometry
        Ready,
        Dirty, // Needs regeneration (LOD changed, etc.)
        PendingUnload
    };
    State state = State::Unloaded;

    bool isReady() const { return state == State::Ready; }
    bool isDirty() const { return state == State::Dirty; }
};

/**
 * @brief Configuration for terrain generation.
 */
struct TerrainConfig {
    float chunkWorldSize = 64.0f;     // World units per chunk edge
    uint32_t chunkResolution = 33;    // Vertices per edge (power of 2 + 1 for seamless LOD)
    float heightScale = 100.0f;       // Maximum terrain height
    float terrainWorldSize = 1024.0f; // Total terrain size for heightmap mapping
    uint32_t maxLoadedChunks = 256;

    // Derived values
    uint32_t quadsPerEdge() const { return chunkResolution - 1; }
    uint32_t verticesPerChunk() const { return chunkResolution * chunkResolution; }
    uint32_t indicesPerChunk() const { return quadsPerEdge() * quadsPerEdge() * 6; }
    float vertexSpacing() const { return chunkWorldSize / static_cast<float>(chunkResolution - 1); }
};

} // namespace Rapture

namespace std {
template <> struct hash<glm::ivec2> {
    size_t operator()(const glm::ivec2 &v) const noexcept
    {
        size_t h1 = hash<int>{}(v.x);
        size_t h2 = hash<int>{}(v.y);
        return h1 ^ (h2 << 1);
    }
};
} // namespace std

#endif // RAPTURE__TERRAIN_TYPES_H
