#ifndef RAPTURE__MATERIAL_PARAMETERS_H
#define RAPTURE__MATERIAL_PARAMETERS_H

namespace Rapture {

enum class ParameterID {
    ALBEDO,
    ROUGHNESS,
    METALLIC,
    AO,
    EMISSIVE,
    EMISSIVE_STRENGTH,
    ALPHA,

    ALBEDO_MAP,
    NORMAL_MAP,
    METALLIC_ROUGHNESS_MAP,
    AO_MAP,
    EMISSIVE_MAP,
    HEIGHT_MAP,
    SPECULAR_MAP
};

} // namespace Rapture

#endif // RAPTURE__MATERIAL_PARAMETERS_H
